#!/usr/bin/env ruby
# == NAME
# script.rb
#
# = DESCRIPTION
# Script to check all cluster in epitracker and compute minimum spanning tree if missing
# This is done across all cluster distances and analyses
#
# == AUTHOR
#  Marc Hoeppner, mphoeppner@gmail.com

require 'optparse'
require 'ostruct'
require 'epitracker'
require 'zlib'
require 'base64'

### Get the script arguments and open relevant files
options = OpenStruct.new()
opts = OptionParser.new()
opts.on("-i","--infile", "=INFILE","Input file") {|argument| options.infile = argument }
opts.on("-d","--db", "=DB","Path to db file") {|argument| options.db = argument }
opts.on("-o","--outfile", "=OUTFILE","Output file") {|argument| options.outfile = argument }
opts.on("-h","--help","Display the usage information") {
    puts opts
    exit
}

opts.parse! 

options.db ? db_file = options.db : db_file = "/work_syn/ngs/projects/epitracker/db/development.sqlite3"

chewbbaca_container = "/work_syn/shared/singularity_cache/depot.galaxyproject.org-singularity-chewbbaca-3.3.10--pyhdfd78af_0.img"
reportree_container = "/work_syn/shared/singularity_cache/mhoeppner-reportree-2.6.0.img"

Epitracker::DBConnection.connect({database: db_file})

log = Logger.new File.open('minimum_spanning_tree.log', 'w')
log.level = Logger::INFO

clusters = Epitracker::Cluster.all

clusters.each do |cluster|
  
    # Welche analysen wurden durchgeführt
    xref_analysis_partitions_clusters = cluster.xref_analysis_partition_clusters
    
    xref_analysis_partitions_clusters.each do |xref_apc|

        # Skip if this cross-link already has the tree object. 
        
        if xref_apc.tree
          warn "This Cluster (#{cluster.name}, #{cluster.cgmlst_partition.cgmlst_schema.organism.name}) and analysis already have a tree - skipping"
          next
        end

        # cluster distance to look at
        xref_ap = xref_apc.xref_analysis_partition
        analysis = xref_ap.cluster_analysis

        # Cross-reference between  analysis, distance and cgMLST profiles for this cluster and clustering distance
        xref_profiles = Epitracker::XrefProfileAnalysisPartitionCluster.where(xref_analysis_partition_id: xref_ap.id, cluster_id: cluster.id )

        profiles = xref_profiles.map {|x| x.cgmlst_profile }
        samples = profiles.map {|profile| profile.assembly.sample}

        # Can't build a tree for less than 3 samples
        next if samples.length < 3

        sample_list = samples.map {|s| s.name }.join(",")
        log.info "#{cluster.name}\t#{analysis.id}\t#{analysis.cgmlst_schema.name}\t#{sample_list}"

        # Dump profiles to tsv files so we can run Chewbbaca on them 
        profiles.each do |profile|
          f = File.new("#{profile.assembly.sample.name}.tsv", "w+")
          matrix = Zlib.inflate(Base64.decode64(profile.profile))
          f.puts matrix
          f.close
        end

        # Step 1: Join profiles into one matrix
        log.info "Running JoinProfiles"
        # Chewbbaca join profiles
        command = "singularity exec #{chewbbaca_container} chewBBACA.py JoinProfiles -p *.tsv -o alleles.tsv &> /dev/null"
        system(command)

        # Reduce matrix to informative positions and set various non-hit characters to 0
        log.info "Running ExtractCgmlst"
        # Chewbbaca clean matrix
        command = "singularity exec #{chewbbaca_container} chewBBACA.py ExtractCgMLST -i alleles.tsv --t 0 -o filtered &> /dev/null "
        system(command)

        # Run Reportree on clean matrix with settings as used by Bella
        log.info "Running Reportree"
        command = "singularity exec #{reportree_container} reportree.py -a filtered/cgMLST0.tsv -out cluster_#{cluster.id} --HC-threshold single-1-50 --loci-called 0.95 --analysis HC &> /dev/null"
        system(command)

        # Read the resulting tree file
        nwk_file = "cluster_#{cluster.id}_single_HC.nwk"
        tree = IO.readlines(nwk_file).join

        # Compress that tree to binary
        compressed_tree = Zlib::Deflate.deflate(tree)
        encoded_tree = Base64.encode64(compressed_tree)

        # Store tree in database
        xref_apc.tree = encoded_tree
        xref_apc.save

        # Remove all files generated by this script and continue with next cluster
        system("rm -R *.tsv *.txt *.nwk filtered")

    end
    
end