#!/usr/bin/env ruby
# == NAME
# script.rb
#
# == AUTHOR
#  Marc Hoeppner, mphoeppner@gmail.com

require 'optparse'
require 'ostruct'
require 'date'
require 'epitracker'
require 'logger'

def run_command(cmd)

    warn cmd

end

### Get the script arguments and open relevant files
options = OpenStruct.new()
opts = OptionParser.new()
opts.on("-i","--infile", "=SETID","Get info for this set") {|argument| options.set_id = argument }
opts.on("-o","--outfile", "=OUTFILE","Output file") {|argument| options.outfile = argument }
opts.on("-d","--db", "=DB","Path to db file") {|argument| options.db = argument }
opts.on("-h","--help","Display the usage information") {
    puts opts
    exit
}

opts.parse! 

options.db ? db_file = options.db : db_file = "/work_syn/ngs/projects/epitracker/db/development.sqlite3"

log = Logger.new File.open('epitracker_wrapper.log', 'w')
log.level = Logger::INFO

log.info "Connecting to database on #{db_file}"

Epitracker::DBConnection.connect({database: db_file})

# list of prerequisites
BASEDIR = "/work_syn/ngs/outbreak/epitracker"
DATADIR = "/work_syn/ngs/analyses"
GABI_TO_EPITRACKER = "/home/mhoeppner/git/scripts/epitracker/gabi2epitracker.rb"
BELLA_VERSION = "1.0.1"
BELLA_CREATE_ANALYSIS = "/home/mhoeppner/git/scripts/epitracker/create_analysis.rb"

configs = {
    "ecoli" => {
        "schema" => "escherichia --efsa"
    },
    "listeria" => {
        "schema" => "listeria"
    },
    "senterica" => {
        "schema" => "salmonella --efsa"
    }
}

runs = {}

worksheet = []
gabi_folders = Dir["#{DATADIR}/2*_M*/gabi_1.3.0/*/results"].map {|f| File.expand_path(f)}

# ------------------------------------------------
# Check if any of the GABI results are not yet in the database
# ------------------------------------------------

log.info "Checking GABI result folders for new samples"

gabi_folders.each do |path|

    basename = path.split("/")[-4]

    samples = Dir["#{path}/samples/*"].map {|f| File.basename(f)}
    
    is_processed = false

    samples.each do |sample|
        next if is_processed
        db = Epitracker::Sample.find_by_name(sample)
        if db
            is_processed = true
        end
    end

    if !is_processed
        log.info "GABI run #{basename} not yet in database, adding to worksheet."        
        worksheet << path
    end

end

log.info "Found #{worksheet} new worksheet entries."

# Load all the new samples into the database
worksheet.each do |path|

    basename = path.split("/")[-4]
    log_name = "#{basename}_gabi2epitracker.log"

    log.info "Loading #{basename} into database"

    # Load the assemblies into the database
    command = "ruby #{GABI_TO_EPITRACKER} -i #{path} &> #{log_name}"
    run_command(command)

end

organisms = Epitracker::Organism.all

# Check for each organism if a new Bella analysis is required
organisms.each do |o|

    default_schema = o.cgmlst_schema.first
    latest_analysis = default_schema.cluster_analyses.last
    latest_sample = o.samples.last

    # Run Bella if the latest sample is newer than the latest analysis
    if !latest_analysis or latest_sample.created_at > latest_analysis.created_at
        
        this_date = Date.today.strftim("%F")
        run_dir = "#{BASEDIR}/#{o.name}/#{this_date}"
        analysis_dir = "#{run_dir}/data"
        command = "mkdir -p #{analysis_dir}"
        run_command(command)

        Dir.chdir(run_dir) do |dir|
            
            Dir.chdir(analysis_dir) do |adir|
                command = "ruby #{BELLA_CREATE_ANALYSIS} -s #{default_schema.name} &> #{default_schema}_create_anaysis.log"
                run_command(command)
            end

            # Execute the pipeline script generated by bella create analysis
            command = "bash data/run.sh &> #{default_schema}_run_bella.log"
            run_command(command)
        end
       
    end
end